# Generated by Django 5.0.1 on 2024-03-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(default='empty', max_length=100)),
                ('forms_name', models.CharField(default='value', max_length=255)),
                ('Rediretpath_name', models.CharField(default='value', max_length=100)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WebTabs.project')),
            ],
        ),
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('field_key', models.CharField(default='empty', max_length=100)),
                ('field_value', models.CharField(default='value', max_length=255)),
                ('selection_value', models.CharField(default='value', max_length=100)),
                ('required', models.BooleanField(default=None, null=True)),
                ('readable', models.BooleanField(default=None, null=True)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WebTabs.project')),
            ],
        ),
    ]
