# Generated by Django 5.0.1 on 2024-03-22 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0002_draggabledata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draggabledata',
            old_name='field_name',
            new_name='fieldid',
        ),
        migrations.RenameField(
            model_name='draggabledata',
            old_name='field_type',
            new_name='formid',
        ),
        migrations.AddField(
            model_name='draggabledata',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebTabs.project'),
        ),
    ]
