# Generated by Django 5.0.1 on 2024-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0003_rename_field_name_draggabledata_fieldid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='field_key',
            field=models.CharField(default='empty', max_length=255),
        ),
    ]
