# Generated by Django 5.0.1 on 2024-03-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTabs', '0005_alter_fielddata_field_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='field_key',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
